# Generated by Django 6.0.3 on 2026-03-26 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("designation", models.CharField(max_length=100)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profiles",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "db_table": "staff_profiles",
                "ordering": ["designation", "employee_id"],
            },
        ),
    ]
