# Generated by Django 6.0.3 on 2026-03-31 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DentalChart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dental_chart",
                        to="consultations.consultation",
                    ),
                ),
            ],
            options={
                "db_table": "dental_charts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToothRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tooth_number", models.CharField(max_length=10)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("SOUND", "Sound"),
                            ("CARIES", "Caries"),
                            ("FILLED", "Filled"),
                            ("MISSING", "Missing"),
                            ("FRACTURED", "Fractured"),
                            ("MOBILE", "Mobile"),
                            ("ROOT_STUMP", "Root Stump"),
                            ("IMPACTED", "Impacted"),
                            ("ATTRITION", "Attrition"),
                            ("ABRASION", "Abrasion"),
                            ("ABFRACTION", "Abfraction"),
                            ("DISCOLORED", "Discolored"),
                        ],
                        max_length=30,
                    ),
                ),
                ("surfaces", models.JSONField(blank=True, default=list)),
                (
                    "mobility_grade",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("percussion_tenderness", models.BooleanField(default=False)),
                ("palpation_tenderness", models.BooleanField(default=False)),
                (
                    "probing_depth_summary",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tooth_records",
                        to="odontology.dentalchart",
                    ),
                ),
            ],
            options={
                "db_table": "tooth_records",
                "ordering": ["tooth_number"],
                "unique_together": {("chart", "tooth_number")},
            },
        ),
    ]
