# Generated by Django 6.0.3 on 2026-04-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odontology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="toothrecord",
            name="exam_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
