# Generated by Django 6.0.3 on 2026-03-31 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cdss", "0001_initial"),
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cdssengine",
            name="consultation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cdss",
                to="consultations.consultation",
            ),
        ),
        migrations.AddField(
            model_name="cdssrecommendation",
            name="cdss_engine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cdss_recommendations",
                to="cdss.cdssengine",
            ),
        ),
    ]
