# Generated by Django 6.0.3 on 2026-04-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdss", "0003_cdssengine_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="cdssengine",
            name="confidence",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cdssengine",
            name="icd_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cdssengine",
            name="per_tooth_results",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
