# Generated by Django 6.0.3 on 2026-03-31 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("clinics", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("consultation_number", models.CharField(max_length=50, unique=True)),
                ("consultation_date", models.DateField()),
                ("consultation_time", models.TimeField()),
                ("chief_complaint", models.TextField(blank=True, null=True)),
                ("history_of_present_illness", models.TextField(blank=True, null=True)),
                ("medical_history_summary", models.TextField(blank=True, null=True)),
                ("dental_history_summary", models.TextField(blank=True, null=True)),
                ("examination_summary", models.TextField(blank=True, null=True)),
                ("provisional_diagnosis", models.TextField(blank=True, null=True)),
                ("final_diagnosis", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "consultations",
                "ordering": ["-consultation_date", "-consultation_time"],
            },
        ),
    ]
