# Generated by Django 6.0.3 on 2026-04-26 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="allergies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="consultation",
            name="complaint_duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="complaint_severity",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="current_medications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="family_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="habits",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="consultation",
            name="hospitalization_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="opd_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="past_dental_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="consultation",
            name="reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="systemic_conditions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="consultation",
            name="visit_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="ToothComplaint",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tooth_number", models.CharField(max_length=10)),
                ("complaint_codes", models.JSONField(blank=True, default=list)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("severity", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tooth_complaints",
                        to="consultations.consultation",
                    ),
                ),
            ],
            options={
                "db_table": "tooth_complaints",
                "ordering": ["tooth_number"],
                "unique_together": {("consultation", "tooth_number")},
            },
        ),
    ]
