# Generated by Django 6.0.3 on 2026-04-20 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="field_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="new_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="old_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="record_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
